### ISSUE TITLE
Almond + Electron

### ISSUE THREAD

**Issue by paul321** [requirejs/almond#119]
Almond JS doesn't work with Electron apps, the library is overriding the NodeJS require function and the app cannot include native modules like require('electron') 

Can we rename the require function from Almond to requirejs ?

**Comment by jrburke** [comment]
You could wrap the code that uses almond in a closure so that the require/requirejs/define variables it uses are just usable inside that closure. If using the r.js optimizer to build the almond bundle, the [wrap or wrap.start/end or wrap.startFile/endFile](https://github.com/requirejs/r.js/blob/db3d0b00177d8cb05c3714daa97d8447e294cffc/build/example.build.js#L461) build options can help with that.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by paul321** [comment]
I'm using grunt task to build production js. Could you give me some example how to use this closure?

Thank you

**Comment by jrburke** [comment]
It depends on the kind of grunt task that is being used, but basically, if you are not using r.js to generate the bundle, you can prepend a `(function(){` and append `}());` to the generated file, that would be the same result as the wrap config.

**Comment by paul321** [comment]
I'm using grunt-contrib-requirejs task which i guess is using r.js to
generate the bundle, so can i use Almond JS?

**Comment by jrburke** [comment]
I'm not very familiar with the grunt task, but I believe it allows passing the same config properties that r.js uses through it, so it should be able to use the wrap config properties mentioned above.
